(function () {
    'use strict';

    angular.module("app.core")
        .factory("CoreService",CoreService);

    function CoreService() {
        var service = {};

        service.genreList = [
            {id:"Other",name:"Other"},
            {id:"Adventure",name:"Adventure"},
            {id:"Animals",name:"Animals"},
            {id:"Art and design",name:"Art and design"},
            {id:"Audiobooks",name:"Audiobooks"},
            {id:"Autobiography and memoir",name:"Autobiography and memoir"},
            {id:"Ballet",name:"Ballet"},
            {id:"Biography",name:"Biography"},
            {id:"Children and teenagers",name:"Children and teenagers"},
            {id:"Business and finance",name:"Business and finance"},
            {id:"Chick lit",name:"Chick lit"},
            {id:"Children's books: 7 and under",name:"Children's books: 7 and under"},
            {id:"Children's fantasy books",name:"Children's fantasy books"},
            {id:"Children's books: 8-12 years",name:"Children's books: 8-12 years"},
            {id:"Classics",name:"Classics"},
            {id:"Comics and graphic novels",name:"Comics and graphic novels"},
            {id:"Computing and IT",name:"Computing and IT"},
            {id:"Craft and hobbies",name:"Craft and hobbies"},
            {id:"Crime fiction",name:"Crime fiction"},
            {id:"Disaster fiction",name:"Disaster fiction"},
            {id:"Dystopian fiction",name:"Dystopian fiction"},
            {id:"Education",name:"Education"},
            {id:"Exam preparation",name:"Exam preparation"},
            {id:"Fairies",name:"Fairies"},
            {id:"Fantasy",name:"Fantasy"},
            {id:"Fiction",name:"Fiction"},
            {id:"Film",name:"Film"},
            {id:"Food and drink",name:"Food and drink"},
            {id:"Friendship",name:"Friendship"},
            {id:"Funny books",name:"Funny books"},
            {id:"Health, mind and body",name:"Health, mind and body"},
            {id:"Historical fiction",name:"Historical fiction"},
            {id:"History",name:"History"},
            {id:"Horror",name:"Horror"},
            {id:"House and garden",name:"House and garden"},
            {id:"Literary criticism",name:"Literary criticism"},
            {id:"Music",name:"Music"},
            {id:"Nature",name:"Nature"},
            {id:"Non-fiction",name:"Non-fiction"},
            {id:"Paranormal romance",name:"Paranormal romance"},
            {id:"Philosophy",name:"Philosophy"},
            {id:"Picture books",name:"Picture books"},
            {id:"Poetry",name:"Poetry"},
            {id:"Politics",name:"Politics"},
            {id:"Reference and languages",name:"Reference and languages"},
            {id:"Religion",name:"Religion"},
            {id:"Romance",name:"Romance"},
            {id:"School",name:"School"},
            {id:"Sci-fi",name:"Sci-fi"},
            {id:"Science and nature",name:"Science and nature"},
            {id:"Play",name:"Play"},
            {id:"Short stories",name:"Short stories"},
            {id:"Society",name:"Society"},
            {id:"Sport and leisure",name:"Sport and leisure"},
            {id:"Stage",name:"Stage"},
            {id:"Teen books",name:"Teen books"},
            {id:"Teen romance",name:"Teen romance"},
            {id:"Thriller",name:"Thriller"},
            {id:"Travel guides",name:"Travel guides"},
            {id:"Travel writing",name:"Travel writing"},
            {id:"True crime",name:"True crime"},
            {id:"TV and radio books",name:"TV and radio books"},
            {id:"Vampires",name:"Vampires"},
            {id:"War",name:"War"},
            {id:"Witches, wizards and magic",name:"Witches, wizards and magic"},
        ]


        service.bookConditionList = [
            { id: 1, name:"Brand new"},
            { id: 2, name:"Used but quite good"},
            { id: 3, name:"Used, slightly old, but readable"}
        ];

        service.bookStatusList = [
            { id: 0, name:"Pending"},
            { id: 1, name:"Auctioned"},
            { id: 2, name:"Dealt"},
            { id: 3, name:"Sold"}
        ];

        service.currencyList = [
            {letter:'AED',name:'UAE Dirham'},
            {letter:'AFN',name:'Afghani'},
            {letter:'ALL',name:'Lek'},
            {letter:'AMD',name:'Armenian Dram'},
            {letter:'ANG',name:'Netherlands Antillian Guilder'},
            {letter:'AOA',name:'Kwanza'},
            {letter:'ARS',name:'Argentine Peso'},
            {letter:'AUD',name:'Australian Dollar'},
            {letter:'AWG',name:'Aruban Guilder'},
            {letter:'AZN',name:'Azerbaijanian Manat'},
            {letter:'BAM',name:'Convertible Marks'},
            {letter:'BBD',name:'Barbados Dollar'},
            {letter:'BDT',name:'Taka'},
            {letter:'BGN',name:'Bulgarian Lev'},
            {letter:'BHD',name:'Bahraini Dinar'},
            {letter:'BIF',name:'Burundi Franc'},
            {letter:'BMD',name:'Bermudian Dollar'},
            {letter:'BND',name:'Brunei Dollar'},
            {letter:'BOB',name:'Boliviano'},
            {letter:'BOV',name:'Mvdol'},
            {letter:'BRL',name:'Brazilian Real'},
            {letter:'BSD',name:'Bahamian Dollar'},
            {letter:'BTN',name:'Ngultrum'},
            {letter:'BWP',name:'Pula'},
            {letter:'BYR',name:'Belarussian Ruble'},
            {letter:'BZD',name:'Belize Dollar'},
            {letter:'CAD',name:'Canadian Dollar'},
            {letter:'CDF',name:'Congolese Franc'},
            {letter:'CHE',name:'WIR Euro'},
            {letter:'CHF',name:'Swiss Franc'},
            {letter:'CHW',name:'WIR Franc'},
            {letter:'CLF',name:'Unidades de fomento'},
            {letter:'CLP',name:'Chilean Peso'},
            {letter:'CNY',name:'Yuan Renminbi'},
            {letter:'COP',name:'Colombian Peso'},
            {letter:'COU',name:'Unidad de Valor Real'},
            {letter:'CRC',name:'Costa Rican Colon'},
            {letter:'CUP',name:'Cuban Peso'},
            {letter:'CVE',name:'Cape Verde Escudo'},
            {letter:'CYP',name:'Cyprus Pound'},
            {letter:'CZK',name:'Czech Koruna'},
            {letter:'DJF',name:'Djibouti Franc'},
            {letter:'DKK',name:'Danish Krone'},
            {letter:'DOP',name:'Dominican Peso'},
            {letter:'DZD',name:'Algerian Dinar'},
            {letter:'EEK',name:'Kroon'},
            {letter:'EGP',name:'Egyptian Pound'},
            {letter:'ERN',name:'Nakfa'},
            {letter:'ETB',name:'Ethiopian Birr'},
            {letter:'EUR',name:'Euro'},
            {letter:'FJD',name:'Fiji Dollar'},
            {letter:'FKP',name:'Falkland Islands Pound'},
            {letter:'GBP',name:'Pound Sterling'},
            {letter:'GEL',name:'Lari'},
            {letter:'GHS',name:'Ghana Cedi'},
            {letter:'GIP',name:'Gibraltar Pound'},
            {letter:'GMD',name:'Dalasi'},
            {letter:'GNF',name:'Guinea Franc'},
            {letter:'GTQ',name:'Quetzal'},
            {letter:'GYD',name:'Guyana Dollar'},
            {letter:'HKD',name:'Hong Kong Dollar'},
            {letter:'HNL',name:'Lempira'},
            {letter:'HRK',name:'Croatian Kuna'},
            {letter:'HTG',name:'Gourde'},
            {letter:'HUF',name:'Forint'},
            {letter:'IDR',name:'Rupiah'},
            {letter:'ILS',name:'New Israeli Sheqel'},
            {letter:'INR',name:'Indian Rupee'},
            {letter:'IQD',name:'Iraqi Dinar'},
            {letter:'IRR',name:'Iranian Rial'},
            {letter:'ISK',name:'Iceland Krona'},
            {letter:'JMD',name:'Jamaican Dollar'},
            {letter:'JOD',name:'Jordanian Dinar'},
            {letter:'JPY',name:'Yen'},
            {letter:'KES',name:'Kenyan Shilling'},
            {letter:'KGS',name:'Som'},
            {letter:'KHR',name:'Riel'},
            {letter:'KMF',name:'Comoro Franc'},
            {letter:'KPW',name:'North Korean Won'},
            {letter:'KRW',name:'Won'},
            {letter:'KWD',name:'Kuwaiti Dinar'},
            {letter:'KYD',name:'Cayman Islands Dollar'},
            {letter:'KZT',name:'Tenge'},
            {letter:'LAK',name:'Kip'},
            {letter:'LBP',name:'Lebanese Pound'},
            {letter:'LKR',name:'Sri Lanka Rupee'},
            {letter:'LRD',name:'Liberian Dollar'},
            {letter:'LSL',name:'Loti'},
            {letter:'LTL',name:'Lithuanian Litas'},
            {letter:'LVL',name:'Latvian Lats'},
            {letter:'LYD',name:'Libyan Dinar'},
            {letter:'MAD',name:'Moroccan Dirham'},
            {letter:'MDL',name:'Moldovan Leu'},
            {letter:'MGA',name:'Malagasy Ariary'},
            {letter:'MKD',name:'Denar'},
            {letter:'MMK',name:'Kyat'},
            {letter:'MNT',name:'Tugrik'},
            {letter:'MOP',name:'Pataca'},
            {letter:'MRO',name:'Ouguiya'},
            {letter:'MTL',name:'Maltese Lira'},
            {letter:'MUR',name:'Mauritius Rupee'},
            {letter:'MVR',name:'Rufiyaa'},
            {letter:'MWK',name:'Kwacha'},
            {letter:'MXN',name:'Mexican Peso'},
            {letter:'MXV',name:'Mexican Unidad de Inversion (UDI)'},
            {letter:'MYR',name:'Malaysian Ringgit'},
            {letter:'MZN',name:'Metical'},
            {letter:'NAD',name:'Namibia Dollar'},
            {letter:'NGN',name:'Naira'},
            {letter:'NIO',name:'Cordoba Oro'},
            {letter:'NOK',name:'Norwegian Krone'},
            {letter:'NPR',name:'Nepalese Rupee'},
            {letter:'NZD',name:'New Zealand Dollar'},
            {letter:'OMR',name:'Rial Omani'},
            {letter:'PAB',name:'Balboa'},
            {letter:'PEN',name:'Nuevo Sol'},
            {letter:'PGK',name:'Kina'},
            {letter:'PHP',name:'Philippine Peso'},
            {letter:'PKR',name:'Pakistan Rupee'},
            {letter:'PLN',name:'Zloty'},
            {letter:'PYG',name:'Guarani'},
            {letter:'QAR',name:'Qatari Rial'},
            {letter:'RON',name:'New Leu'},
            {letter:'RSD',name:'Serbian Dinar'},
            {letter:'RUB',name:'Russian Ruble'},
            {letter:'RWF',name:'Rwanda Franc'},
            {letter:'SAR',name:'Saudi Riyal'},
            {letter:'SBD',name:'Solomon Islands Dollar'},
            {letter:'SCR',name:'Seychelles Rupee'},
            {letter:'SDG',name:'Sudanese Pound'},
            {letter:'SEK',name:'Swedish Krona'},
            {letter:'SGD',name:'Singapore Dollar'},
            {letter:'SHP',name:'Saint Helena Pound'},
            {letter:'SLL',name:'Leone'},
            {letter:'SOS',name:'Somali Shilling'},
            {letter:'SRD',name:'Surinam Dollar'},
            {letter:'STD',name:'Dobra'},
            {letter:'SVC',name:'El Salvador Colon'},
            {letter:'SYP',name:'Syrian Pound'},
            {letter:'SZL',name:'Lilangeni'},
            {letter:'THB',name:'Baht'},
            {letter:'TJS',name:'Somoni'},
            {letter:'TMM',name:'Manat'},
            {letter:'TND',name:'Tunisian Dinar'},
            {letter:'TOP',name:'Pa\'anga'},
            {letter:'TRY',name:'New Turkish Lira'},
            {letter:'TTD',name:'Trinidad and Tobago Dollar'},
            {letter:'TWD',name:'New Taiwan Dollar'},
            {letter:'TZS',name:'Tanzanian Shilling'},
            {letter:'UAH',name:'Hryvnia'},
            {letter:'UGX',name:'Uganda Shilling'},
            {letter:'USD',name:'US Dollar'},
            {letter:'USN',name:'US Dollar (Next day)'},
            {letter:'USS',name:'US Dollar (Same day)'},
            {letter:'UYI',name:'Uruguay Peso en Unidades Indexadas'},
            {letter:'UYU',name:'Peso Uruguayo'},
            {letter:'UZS',name:'Uzbekistan Sum'},
            {letter:'VEF',name:'Bolivar Fuerte'},
            {letter:'VND',name:'Dong'},
            {letter:'VUV',name:'Vatu'},
            {letter:'WST',name:'Tala'},
            {letter:'XAF',name:'CFA Franc BEAC'},
            {letter:'XAG',name:'Silver'},
            {letter:'XAU',name:'Gold'},
            {letter:'XBA',name:'European Composite Unit (EURCO)'},
            {letter:'XBB',name:'European Monetary Unit (E.M.U.-6)'},
            {letter:'XBC',name:'European Unit of Account 9 (E.U.A.-9)'},
            {letter:'XBD',name:'European Unit of Account 17 (E.U.A.-17)'},
            {letter:'XCD',name:'East Caribbean Dollar'},
            {letter:'XDR',name:'Special Drawing Rights'},
            {letter:'XFO',name:'Gold-Franc'},
            {letter:'XFU',name:'UIC-Franc'},
            {letter:'XOF',name:'CFA Franc BCEAO'},
            {letter:'XPD',name:'Palladium'},
            {letter:'XPF',name:'CFP Franc'},
            {letter:'XPT',name:'Platinum'},
            {letter:'XTS',name:'Code for testing purposes'},
            {letter:'XXX',name:'No currency'},
            {letter:'YER',name:'Yemeni Rial'},
            {letter:'ZAR',name:'Rand'},
            {letter:'ZMK',name:'Zambian Kwacha'},
            {letter:'ZWD',name:'Zimbabwe Dollar'},
        ]
        
        
        service.countryList = [
            {id:"AF",name:"Afghanistan"},
            {id:"AX",name:"Åland Islands"},
            {id:"AL",name:"Albania"},
            {id:"DZ",name:"Algeria"},
            {id:"AS",name:"American Samoa"},
            {id:"AD",name:"Andorra"},
            {id:"AO",name:"Angola"},
            {id:"AI",name:"Anguilla"},
            {id:"AQ",name:"Antarctica"},
            {id:"AG",name:"Antigua and Barbuda"},
            {id:"AR",name:"Argentina"},
            {id:"AM",name:"Armenia"},
            {id:"AW",name:"Aruba"},
            {id:"AU",name:"Australia"},
            {id:"AT",name:"Austria"},
            {id:"AZ",name:"Azerbaijan"},
            {id:"BS",name:"Bahamas"},
            {id:"BH",name:"Bahrain"},
            {id:"BD",name:"Bangladesh"},
            {id:"BB",name:"Barbados"},
            {id:"BY",name:"Belarus"},
            {id:"BE",name:"Belgium"},
            {id:"BZ",name:"Belize"},
            {id:"BJ",name:"Benin"},
            {id:"BM",name:"Bermuda"},
            {id:"BT",name:"Bhutan"},
            {id:"BO",name:"Bolivia"},
            {id:"BQ",name:"Bonaire, Sint Eustatius and Saba"},
            {id:"BA",name:"Bosnia and Herzegovina"},
            {id:"BW",name:"Botswana"},
            {id:"BV",name:"Bouvet Island"},
            {id:"BR",name:"Brazil"},
            {id:"IO",name:"British Indian Ocean Territory"},
            {id:"BN",name:"Brunei"},
            {id:"BG",name:"Bulgaria"},
            {id:"BF",name:"Burkina Faso"},
            {id:"BI",name:"Burundi"},
            {id:"CV",name:"Cabo Verde"},
            {id:"KH",name:"Cambodia"},
            {id:"CM",name:"Cameroon"},
            {id:"CA",name:"Canada"},
            {id:"KY",name:"Cayman Islands"},
            {id:"CF",name:"Central African Republic"},
            {id:"TD",name:"Chad"},
            {id:"CL",name:"Chile"},
            {id:"CN",name:"China"},
            {id:"CX",name:"Christmas Island"},
            {id:"CC",name:"Cocos (Keeling) Islands"},
            {id:"CO",name:"Colombia"},
            {id:"KM",name:"Comoros"},
            {id:"CG",name:"Congo"},
            {id:"CD",name:"Congo (the Democratic Republic of the)"},
            {id:"CK",name:"Cook Islands"},
            {id:"CR",name:"Costa Rica"},
            {id:"CI",name:"Côte d'Ivoire"},
            {id:"HR",name:"Croatia"},
            {id:"CU",name:"Cuba"},
            {id:"CW",name:"Curaçao"},
            {id:"CY",name:"Cyprus"},
            {id:"CZ",name:"Czech Republic"},
            {id:"DK",name:"Denmark"},
            {id:"DJ",name:"Djibouti"},
            {id:"DM",name:"Dominica"},
            {id:"DO",name:"Dominican Republic"},
            {id:"EC",name:"Ecuador"},
            {id:"EG",name:"Egypt"},
            {id:"SV",name:"El Salvador"},
            {id:"GQ",name:"Equatorial Guinea"},
            {id:"ER",name:"Eritrea"},
            {id:"EE",name:"Estonia"},
            {id:"ET",name:"Ethiopia"},
            {id:"FK",name:"Falkland Islands  [Malvinas]"},
            {id:"FO",name:"Faroe Islands"},
            {id:"FJ",name:"Fiji"},
            {id:"FI",name:"Finland"},
            {id:"FR",name:"France"},
            {id:"GF",name:"French Guiana"},
            {id:"PF",name:"French Polynesia"},
            {id:"TF",name:"French Southern Territories"},
            {id:"GA",name:"Gabon"},
            {id:"GM",name:"Gambia"},
            {id:"GE",name:"Georgia"},
            {id:"DE",name:"Germany"},
            {id:"GH",name:"Ghana"},
            {id:"GI",name:"Gibraltar"},
            {id:"GR",name:"Greece"},
            {id:"GL",name:"Greenland"},
            {id:"GD",name:"Grenada"},
            {id:"GP",name:"Guadeloupe"},
            {id:"GU",name:"Guam"},
            {id:"GT",name:"Guatemala"},
            {id:"GG",name:"Guernsey"},
            {id:"GN",name:"Guinea"},
            {id:"GW",name:"Guinea-Bissau"},
            {id:"GY",name:"Guyana"},
            {id:"HT",name:"Haiti"},
            {id:"HM",name:"Heard Island and McDonald Islands"},
            {id:"VA",name:"Holy See"},
            {id:"HN",name:"Honduras"},
            {id:"HK",name:"Hong Kong"},
            {id:"HU",name:"Hungary"},
            {id:"IS",name:"Iceland"},
            {id:"IN",name:"India"},
            {id:"ID",name:"Indonesia"},
            {id:"IR",name:"Iran"},
            {id:"IQ",name:"Iraq"},
            {id:"IE",name:"Ireland"},
            {id:"IM",name:"Isle of Man"},
            {id:"IL",name:"Israel"},
            {id:"IT",name:"Italy"},
            {id:"JM",name:"Jamaica"},
            {id:"JP",name:"Japan"},
            {id:"JE",name:"Jersey"},
            {id:"JO",name:"Jordan"},
            {id:"KZ",name:"Kazakhstan"},
            {id:"KE",name:"Kenya"},
            {id:"KI",name:"Kiribati"},
            {id:"KW",name:"Kuwait"},
            {id:"KG",name:"Kyrgyzstan"},
            {id:"LA",name:"Laos"},
            {id:"LV",name:"Latvia"},
            {id:"LB",name:"Lebanon"},
            {id:"LS",name:"Lesotho"},
            {id:"LR",name:"Liberia"},
            {id:"LY",name:"Libya"},
            {id:"LI",name:"Liechtenstein"},
            {id:"LT",name:"Lithuania"},
            {id:"LU",name:"Luxembourg"},
            {id:"MO",name:"Macao"},
            {id:"MK",name:"Macedonia"},
            {id:"MG",name:"Madagascar"},
            {id:"MW",name:"Malawi"},
            {id:"MY",name:"Malaysia"},
            {id:"MV",name:"Maldives"},
            {id:"ML",name:"Mali"},
            {id:"MT",name:"Malta"},
            {id:"MH",name:"Marshall Islands"},
            {id:"MQ",name:"Martinique"},
            {id:"MR",name:"Mauritania"},
            {id:"MU",name:"Mauritius"},
            {id:"YT",name:"Mayotte"},
            {id:"MX",name:"Mexico"},
            {id:"FM",name:"Micronesia (Federated States of)"},
            {id:"MD",name:"Moldova"},
            {id:"MC",name:"Monaco"},
            {id:"MN",name:"Mongolia"},
            {id:"ME",name:"Montenegro"},
            {id:"MS",name:"Montserrat"},
            {id:"MA",name:"Morocco"},
            {id:"MZ",name:"Mozambique"},
            {id:"MM",name:"Myanmar"},
            {id:"NA",name:"Namibia"},
            {id:"NR",name:"Nauru"},
            {id:"NP",name:"Nepal"},
            {id:"NL",name:"Netherlands"},
            {id:"NC",name:"New Caledonia"},
            {id:"NZ",name:"New Zealand"},
            {id:"NI",name:"Nicaragua"},
            {id:"NE",name:"Niger"},
            {id:"NG",name:"Nigeria"},
            {id:"NU",name:"Niue"},
            {id:"NF",name:"Norfolk Island"},
            {id:"KP",name:"North Korea"},
            {id:"MP",name:"Northern Mariana Islands"},
            {id:"NO",name:"Norway"},
            {id:"OM",name:"Oman"},
            {id:"PK",name:"Pakistan"},
            {id:"PW",name:"Palau"},
            {id:"PS",name:"Palestine, State of"},
            {id:"PA",name:"Panama"},
            {id:"PG",name:"Papua New Guinea"},
            {id:"PY",name:"Paraguay"},
            {id:"PE",name:"Peru"},
            {id:"PH",name:"Philippines"},
            {id:"PN",name:"Pitcairn"},
            {id:"PL",name:"Poland"},
            {id:"PT",name:"Portugal"},
            {id:"PR",name:"Puerto Rico"},
            {id:"QA",name:"Qatar"},
            {id:"RE",name:"Réunion"},
            {id:"RO",name:"Romania"},
            {id:"RU",name:"Russia"},
            {id:"RW",name:"Rwanda"},
            {id:"BL",name:"Saint Barthélemy"},
            {id:"SH",name:"Saint Helena, Ascension and Tristan da Cunha"},
            {id:"KN",name:"Saint Kitts and Nevis"},
            {id:"LC",name:"Saint Lucia"},
            {id:"MF",name:"Saint Martin (French part)"},
            {id:"PM",name:"Saint Pierre and Miquelon"},
            {id:"VC",name:"Saint Vincent and the Grenadines"},
            {id:"WS",name:"Samoa"},
            {id:"SM",name:"San Marino"},
            {id:"ST",name:"Sao Tome and Principe"},
            {id:"SA",name:"Saudi Arabia"},
            {id:"SN",name:"Senegal"},
            {id:"RS",name:"Serbia"},
            {id:"SC",name:"Seychelles"},
            {id:"SL",name:"Sierra Leone"},
            {id:"SG",name:"Singapore"},
            {id:"SX",name:"Sint Maarten (Dutch part)"},
            {id:"SK",name:"Slovakia"},
            {id:"SI",name:"Slovenia"},
            {id:"SB",name:"Solomon Islands"},
            {id:"SO",name:"Somalia"},
            {id:"ZA",name:"South Africa"},
            {id:"GS",name:"South Georgia and the South Sandwich Islands"},
            {id:"KR",name:"South Korea"},
            {id:"SS",name:"South Sudan"},
            {id:"ES",name:"Spain"},
            {id:"LK",name:"Sri Lanka"},
            {id:"SD",name:"Sudan"},
            {id:"SR",name:"Suriname:"},
            {id:"SJ",name:"Svalbard and Jan Mayen"},
            {id:"SZ",name:"Swaziland"},
            {id:"SE",name:"Sweden"},
            {id:"CH",name:"Switzerland"},
            {id:"SY",name:"Syria"},
            {id:"TW",name:"Taiwan"},
            {id:"TJ",name:"Tajikistan"},
            {id:"TZ",name:"Tanzania"},
            {id:"TH",name:"Thailand"},
            {id:"TL",name:"Timor-Leste"},
            {id:"TG",name:"Togo"},
            {id:"TK",name:"Tokelau"},
            {id:"TO",name:"Tonga"},
            {id:"TT",name:"Trinidad and Tobago"},
            {id:"TN",name:"Tunisia"},
            {id:"TR",name:"Turkey"},
            {id:"TM",name:"Turkmenistan"},
            {id:"TC",name:"Turks and Caicos Islands"},
            {id:"TV",name:"Tuvalu"},
            {id:"UG",name:"Uganda"},
            {id:"UA",name:"Ukraine"},
            {id:"AE",name:"United Arab Emirates"},
            {id:"GB",name:"United Kingdom"},
            {id:"UM",name:"United States Minor Outlying Islands"},
            {id:"US",name:"United States of America"},
            {id:"UY",name:"Uruguay"},
            {id:"UZ",name:"Uzbekistan"},
            {id:"VU",name:"Vanuatu"},
            {id:"VE",name:"Venezuela"},
            {id:"VN",name:"Vietnam"},
            {id:"VG",name:"Virgin Islands (British)"},
            {id:"VI",name:"Virgin Islands (U.S.)"},
            {id:"WF",name:"Wallis and Futuna"},
            {id:"EH",name:"Western Sahara"},
            {id:"YE",name:"Yemen"},
            {id:"ZM",name:"Zambia"},
            {id:"ZW",name:"Zimbabwe"},
        ]

        service.bookLanguageList = [
            { id:"--",name:"Unknown"},
            { id:"ab",name:"Abkhaz"},
            { id:"aa",name:"Afar"},
            { id:"af",name:"Afrikaans"},
            { id:"ak",name:"Akan"},
            { id:"sq",name:"Albanian"},
            { id:"am",name:"Amharic"},
            { id:"ar",name:"Arabic"},
            { id:"an",name:"Aragonese"},
            { id:"hy",name:"Armenian"},
            { id:"as",name:"Assamese"},
            { id:"av",name:"Avaric"},
            { id:"ae",name:"Avestan"},
            { id:"ay",name:"Aymara"},
            { id:"az",name:"Azerbaijani"},
            { id:"bm",name:"Bambara"},
            { id:"ba",name:"Bashkir"},
            { id:"eu",name:"Basque"},
            { id:"be",name:"Belarusian"},
            { id:"bn",name:"Bengali, Bangla"},
            { id:"bh",name:"Bihari"},
            { id:"bi",name:"Bislama"},
            { id:"bs",name:"Bosnian"},
            { id:"br",name:"Breton"},
            { id:"bg",name:"Bulgarian"},
            { id:"my",name:"Burmese"},
            { id:"ca",name:"Catalan"},
            { id:"ch",name:"Chamorro"},
            { id:"ce",name:"Chechen"},
            { id:"ny",name:"Chichewa, Chewa, Nyanja"},
            { id:"zh",name:"Chinese"},
            { id:"cv",name:"Chuvash"},
            { id:"kw",name:"Cornish"},
            { id:"co",name:"Corsican"},
            { id:"cr",name:"Cree"},
            { id:"hr",name:"Croatian"},
            { id:"cs",name:"Czech"},
            { id:"da",name:"Danish"},
            { id:"dv",name:"Divehi, Dhivehi, Maldivian"},
            { id:"nl",name:"Dutch"},
            { id:"dz",name:"Dzongkha"},
            { id:"en",name:"English"},
            { id:"eo",name:"Esperanto"},
            { id:"et",name:"Estonian"},
            { id:"ee",name:"Ewe"},
            { id:"fo",name:"Faroese"},
            { id:"fj",name:"Fijian"},
            { id:"fi",name:"Finnish"},
            { id:"fr",name:"French"},
            { id:"ff",name:"Fula, Fulah, Pulaar, Pular"},
            { id:"gl",name:"Galician"},
            { id:"ka",name:"Georgian"},
            { id:"de",name:"German"},
            { id:"el",name:"Greek (modern)"},
            { id:"gn",name:"Guarani"},
            { id:"gu",name:"Gujarati"},
            { id:"ht",name:"Haitian, Haitian Creole"},
            { id:"ha",name:"Hausa"},
            { id:"he",name:"Hebrew (modern)"},
            { id:"hz",name:"Herero"},
            { id:"hi",name:"Hindi"},
            { id:"ho",name:"Hiri Motu"},
            { id:"hu",name:"Hungarian"},
            { id:"ia",name:"Interlingua"},
            { id:"id",name:"Indonesian"},
            { id:"ie",name:"Interlingue"},
            { id:"ga",name:"Irish"},
            { id:"ig",name:"Igbo"},
            { id:"ik",name:"Inupiaq"},
            { id:"io",name:"Ido"},
            { id:"is",name:"Icelandic"},
            { id:"it",name:"Italian"},
            { id:"iu",name:"Inuktitut"},
            { id:"ja",name:"Japanese"},
            { id:"jv",name:"Javanese"},
            { id:"kl",name:"Kalaallisut, Greenlandic"},
            { id:"kn",name:"Kannada"},
            { id:"kr",name:"Kanuri"},
            { id:"ks",name:"Kashmiri"},
            { id:"kk",name:"Kazakh"},
            { id:"km",name:"Khmer"},
            { id:"ki",name:"Kikuyu, Gikuyu"},
            { id:"rw",name:"Kinyarwanda"},
            { id:"ky",name:"Kyrgyz"},
            { id:"kv",name:"Komi"},
            { id:"kg",name:"Kongo"},
            { id:"ko",name:"Korean"},
            { id:"ku",name:"Kurdish"},
            { id:"kj",name:"Kwanyama, Kuanyama"},
            { id:"la",name:"Latin"},
            { id:"lb",name:"Luxembourgish, Letzeburgesch"},
            { id:"lg",name:"Ganda"},
            { id:"li",name:"Limburgish, Limburgan, Limburger"},
            { id:"ln",name:"Lingala"},
            { id:"lo",name:"Lao"},
            { id:"lt",name:"Lithuanian"},
            { id:"lu",name:"Luba-Katanga"},
            { id:"lv",name:"Latvian"},
            { id:"gv",name:"Manx"},
            { id:"mk",name:"Macedonian"},
            { id:"mg",name:"Malagasy"},
            { id:"ms",name:"Malay"},
            { id:"ml",name:"Malayalam"},
            { id:"mt",name:"Maltese"},
            { id:"mi",name:"Maori"},
            { id:"mr",name:"Marathi (Marathi)"},
            { id:"mh",name:"Marshallese"},
            { id:"mn",name:"Mongolian"},
            { id:"na",name:"Nauru"},
            { id:"nv",name:"Navajo, Navaho"},
            { id:"nd",name:"Northern Ndebele"},
            { id:"ne",name:"Nepali"},
            { id:"ng",name:"Ndonga"},
            { id:"nb",name:"Norwegian Bokmal"},
            { id:"nn",name:"Norwegian Nynorsk"},
            { id:"no",name:"Norwegian"},
            { id:"ii",name:"Nuosu"},
            { id:"nr",name:"Southern Ndebele"},
            { id:"oc",name:"Occitan"},
            { id:"oj",name:"Ojibwe, Ojibwa"},
            { id:"cu",name:"Old Church Slavonic, Church Slavonic, Old Bulgarian"},
            { id:"om",name:"Oromo"},
            { id:"or",name:"Oriya"},
            { id:"os",name:"Ossetian, Ossetic"},
            { id:"pa",name:"Panjabi, Punjabi"},
            { id:"pi",name:"Pali"},
            { id:"fa",name:"Persian (Farsi)"},
            { id:"pl",name:"Polish"},
            { id:"ps",name:"Pashto, Pushto"},
            { id:"pt",name:"Portuguese"},
            { id:"qu",name:"Quechua"},
            { id:"rm",name:"Romansh"},
            { id:"rn",name:"Kirundi"},
            { id:"ro",name:"Romanian"},
            { id:"ru",name:"Russian"},
            { id:"sa",name:"Sanskrit (Samskrta)"},
            { id:"sc",name:"Sardinian"},
            { id:"sd",name:"Sindhi"},
            { id:"se",name:"Northern Sami"},
            { id:"sm",name:"Samoan"},
            { id:"sg",name:"Sango"},
            { id:"sr",name:"Serbian"},
            { id:"gd",name:"Scottish Gaelic, Gaelic"},
            { id:"sn",name:"Shona"},
            { id:"si",name:"Sinhala, Sinhalese"},
            { id:"sk",name:"Slovak"},
            { id:"sl",name:"Slovene"},
            { id:"so",name:"Somali"},
            { id:"st",name:"Southern Sotho"},
            { id:"es",name:"Spanish"},
            { id:"su",name:"Sundanese"},
            { id:"sw",name:"Swahili"},
            { id:"ss",name:"Swati"},
            { id:"sv",name:"Swedish"},
            { id:"ta",name:"Tamil"},
            { id:"te",name:"Telugu"},
            { id:"tg",name:"Tajik"},
            { id:"th",name:"Thai"},
            { id:"ti",name:"Tigrinya"},
            { id:"bo",name:"Tibetan Standard, Tibetan, Central"},
            { id:"tk",name:"Turkmen"},
            { id:"tl",name:"Tagalog"},
            { id:"tn",name:"Tswana"},
            { id:"to",name:"Tonga (Tonga Islands)"},
            { id:"tr",name:"Turkish"},
            { id:"ts",name:"Tsonga"},
            { id:"tt",name:"Tatar"},
            { id:"tw",name:"Twi"},
            { id:"ty",name:"Tahitian"},
            { id:"ug",name:"Uyghur"},
            { id:"uk",name:"Ukrainian"},
            { id:"ur",name:"Urdu"},
            { id:"uz",name:"Uzbek"},
            { id:"ve",name:"Venda"},
            { id:"vi",name:"Vietnamese"},
            { id:"vo",name:"Volapuk"},
            { id:"wa",name:"Walloon"},
            { id:"cy",name:"Welsh"},
            { id:"wo",name:"Wolof"},
            { id:"fy",name:"Western Frisian"},
            { id:"xh",name:"Xhosa"},
            { id:"yi",name:"Yiddish"},
            { id:"yo",name:"Yoruba"},
            { id:"za",name:"Zhuang, Chuang"},
            { id:"zu",name:"Zulu"},
        ];


        return service;
    }

})();